In [2]:
import pandas as pd

data = {'Name': ['Amit', 'Sunita', 'Raj'],
        'Sales': [12000, 15000, 18000]}

df = pd.DataFrame(data)
df

     Name  Sales
0    Amit  12000
1  Sunita  15000
2     Raj  18000

In [ ]:
import pandas as pd 
data = {
    "name": [
        "Aman", "Riya", "Karan", "Simran", "Rahul",
        "Priya", "Arjun", "Neha", "Vikas", "Anjali",
        "Rohit", "Sneha", "Amit", "Pooja", "Kabir"
    ],
    "age": [
        22, 19, 24, 21, 23,
        20, 25, 22, 26, 21,
        23, 20, 27, 22, 24
    ],
    "city": [
        "Delhi", "Mumbai", "Delhi", "Chandigarh", "Mumbai",
        "Delhi", "Bangalore", "Delhi", "Chandigarh", "Mumbai",
        "Delhi", "Bangalore", "Mumbai", "Delhi", "Chandigarh"
    ],
    "course": [
        "BCA", "BBA", "MCA", "BCA", "BCom",
        "BBA", "MCA", "BCA", "MBA", "BCom",
        "BCA", "MBA", "MCA", "BBA", "BCA"
    ],
    "marks": [
        78, 65, 88, 72, 69,
        74, 91, 80, 85, 68,
        77, 82, 90, 73, 79
    ],
    "college": [
        "DU", "MU", "DU", "PU", "MU",
        "DU", "IIT", "DU", "PU", "MU",
        "DU", "IIT", "MU", "DU", "PU"
    ]
}
df = pd.DataFrame(data)
df

UndefinedVariableError: name 'Delhi' is not defined

In [ ]:
df.query('age>20')

      name  age        city course  marks college
0     Aman   22       Delhi    BCA     78      DU
2    Karan   24       Delhi    MCA     88      DU
3   Simran   21  Chandigarh    BCA     72      PU
4    Rahul   23      Mumbai   BCom     69      MU
6    Arjun   25   Bangalore    MCA     91     IIT
7     Neha   22       Delhi    BCA     80      DU
8    Vikas   26  Chandigarh    MBA     85      PU
9   Anjali   21      Mumbai   BCom     68      MU
10   Rohit   23       Delhi    BCA     77      DU
12    Amit   27      Mumbai    MCA     90      MU
13   Pooja   22       Delhi    BBA     73      DU
14   Kabir   24  Chandigarh    BCA     79      PU